name: ✨ 功能建议
description: 提出新功能或改进建议
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您分享想法！我们很想听听您的功能建议。

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 这个功能要解决什么问题？（可选）
      placeholder: 当我在使用...时，我感到困扰，因为...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 描述您希望的功能
      placeholder: 我希望 Portal 能够...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考虑过的其他解决方案（可选）
      placeholder: 我也考虑过...

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 低 - 有会更好
        - 中 - 会显著改善体验
        - 高 - 目前体验受到严重影响

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 其他相关的上下文或截图
